START TRANSACTION;
    ALTER TABLE category
    ADD COLUMN phone_number VARCHAR NOT NULL DEFAULT '0508233592',
    ADD COLUMN gender VARCHAR NOT NULL DEFAULT 'None',
    ADD COLUMN country VARCHAR NOT NULL DEFAULT 'None';
COMMIT;